### ISSUE TITLE
Support for FMS PID's

### ISSUE THREAD

**Issue by anterosa** [JonnoFTW/OBD-Datalogger#1]
Is it possible to view [rpi-can-logger](https://github.com/JonnoFTW/rpi-can-logger) FMS PID's with app?

**Comment by JonnoFTW** [comment]
It doesn't properly support them at the moment, see: 

https://github.com/JonnoFTW/OBD-Datalogger/blob/master/app/src/main/java/com/jonathan/obd_bt/MainActivity.java#L551

You can add your PIDs to the array if you want.

It also probably won't build on the latest version of Android Studio and may require some fiddling about to get it to build. 

I don't have time right now to update this app.

**Comment by anterosa** [comment]
OK.  I don't have experience with Android programming, so I will test webcan only. Thanks for info!
